### ISSUE TITLE
Deleting a category-  0 categories displayd after

### ISSUE THREAD

**Issue by Renemes** [SmileMeBack/smilemeback#26] opened 2015-06-25 14:36 UTC
When deleting one of the categories other categories will disappear also and gallery view is empty. When you scroll the empty gallery view then the other categories will be shown again correctly.

**Comment by tpetmanson** [comment] 2015-06-26 06:12
Could not reproduce. But might be gridview refresh/reload issue

**Comment by tpetmanson** [comment] 2015-06-28 21:22
closing as no new information about it

**Closed as completed by tpetmanson** 2015-06-28 21:22 UTC
